#include "PluginEditor.h"
VelvetAudioProcessorEditor::VelvetAudioProcessorEditor(VelvetAudioProcessor& p)
    : AudioProcessorEditor(&p), processorRef(p),
      att_INPUT_GAIN(processorRef.apvts,"INPUT_GAIN",knob_INPUT_GAIN),
      att_GAIN_GAIN_DB_T2EC(processorRef.apvts,"GAIN_GAIN_DB_T2EC",knob_GAIN_GAIN_DB_T2EC),
      att_DELAY_DELAY_MS_KENU(processorRef.apvts,"DELAY_DELAY_MS_KENU",knob_DELAY_DELAY_MS_KENU),
      att_DELAY_FEEDBACK_KENU(processorRef.apvts,"DELAY_FEEDBACK_KENU",knob_DELAY_FEEDBACK_KENU),
      att_DELAY_MIX_KENU(processorRef.apvts,"DELAY_MIX_KENU",knob_DELAY_MIX_KENU),
      att_COMPRESSOR_THRESHOLD_WOR8(processorRef.apvts,"COMPRESSOR_THRESHOLD_WOR8",knob_COMPRESSOR_THRESHOLD_WOR8),
      att_COMPRESSOR_RATIO_WOR8(processorRef.apvts,"COMPRESSOR_RATIO_WOR8",knob_COMPRESSOR_RATIO_WOR8),
      att_COMPRESSOR_ATTACK_WOR8(processorRef.apvts,"COMPRESSOR_ATTACK_WOR8",knob_COMPRESSOR_ATTACK_WOR8),
      att_COMPRESSOR_RELEASE_WOR8(processorRef.apvts,"COMPRESSOR_RELEASE_WOR8",knob_COMPRESSOR_RELEASE_WOR8),
      att_COMPRESSOR_MAKEUP_WOR8(processorRef.apvts,"COMPRESSOR_MAKEUP_WOR8",knob_COMPRESSOR_MAKEUP_WOR8),
      att_OUTPUT_GAIN(processorRef.apvts,"OUTPUT_GAIN",knob_OUTPUT_GAIN)
{
    setLookAndFeel(&lnf); setSize(520,400);
    knob_INPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_INPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_INPUT_GAIN.setLookAndFeel(&lnf); knob_INPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_INPUT_GAIN); lbl_INPUT_GAIN.setText("INPUT",juce::dontSendNotification); lbl_INPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_INPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_INPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_INPUT_GAIN);
    knob_GAIN_GAIN_DB_T2EC.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_GAIN_GAIN_DB_T2EC.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_GAIN_GAIN_DB_T2EC.setLookAndFeel(&lnf); knob_GAIN_GAIN_DB_T2EC.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_GAIN_GAIN_DB_T2EC); lbl_GAIN_GAIN_DB_T2EC.setText("GAIN GAIN",juce::dontSendNotification); lbl_GAIN_GAIN_DB_T2EC.setJustificationType(juce::Justification::centred); lbl_GAIN_GAIN_DB_T2EC.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_GAIN_GAIN_DB_T2EC.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_GAIN_GAIN_DB_T2EC);
    knob_DELAY_DELAY_MS_KENU.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_DELAY_DELAY_MS_KENU.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_DELAY_DELAY_MS_KENU.setLookAndFeel(&lnf); knob_DELAY_DELAY_MS_KENU.setDoubleClickReturnValue(true,250.0f); addAndMakeVisible(knob_DELAY_DELAY_MS_KENU); lbl_DELAY_DELAY_MS_KENU.setText("DELAY TIME",juce::dontSendNotification); lbl_DELAY_DELAY_MS_KENU.setJustificationType(juce::Justification::centred); lbl_DELAY_DELAY_MS_KENU.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_DELAY_DELAY_MS_KENU.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_DELAY_DELAY_MS_KENU);
    knob_DELAY_FEEDBACK_KENU.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_DELAY_FEEDBACK_KENU.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_DELAY_FEEDBACK_KENU.setLookAndFeel(&lnf); knob_DELAY_FEEDBACK_KENU.setDoubleClickReturnValue(true,40.0f); addAndMakeVisible(knob_DELAY_FEEDBACK_KENU); lbl_DELAY_FEEDBACK_KENU.setText("DELAY FEEDBACK",juce::dontSendNotification); lbl_DELAY_FEEDBACK_KENU.setJustificationType(juce::Justification::centred); lbl_DELAY_FEEDBACK_KENU.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_DELAY_FEEDBACK_KENU.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_DELAY_FEEDBACK_KENU);
    knob_DELAY_MIX_KENU.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_DELAY_MIX_KENU.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_DELAY_MIX_KENU.setLookAndFeel(&lnf); knob_DELAY_MIX_KENU.setDoubleClickReturnValue(true,30.0f); addAndMakeVisible(knob_DELAY_MIX_KENU); lbl_DELAY_MIX_KENU.setText("DELAY MIX",juce::dontSendNotification); lbl_DELAY_MIX_KENU.setJustificationType(juce::Justification::centred); lbl_DELAY_MIX_KENU.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_DELAY_MIX_KENU.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_DELAY_MIX_KENU);
    knob_COMPRESSOR_THRESHOLD_WOR8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_THRESHOLD_WOR8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_THRESHOLD_WOR8.setLookAndFeel(&lnf); knob_COMPRESSOR_THRESHOLD_WOR8.setDoubleClickReturnValue(true,-18.0f); addAndMakeVisible(knob_COMPRESSOR_THRESHOLD_WOR8); lbl_COMPRESSOR_THRESHOLD_WOR8.setText("COMPRESSOR THRESHOLD",juce::dontSendNotification); lbl_COMPRESSOR_THRESHOLD_WOR8.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_THRESHOLD_WOR8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_THRESHOLD_WOR8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_THRESHOLD_WOR8);
    knob_COMPRESSOR_RATIO_WOR8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RATIO_WOR8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RATIO_WOR8.setLookAndFeel(&lnf); knob_COMPRESSOR_RATIO_WOR8.setDoubleClickReturnValue(true,4.0f); addAndMakeVisible(knob_COMPRESSOR_RATIO_WOR8); lbl_COMPRESSOR_RATIO_WOR8.setText("COMPRESSOR RATIO",juce::dontSendNotification); lbl_COMPRESSOR_RATIO_WOR8.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RATIO_WOR8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RATIO_WOR8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RATIO_WOR8);
    knob_COMPRESSOR_ATTACK_WOR8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_ATTACK_WOR8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_ATTACK_WOR8.setLookAndFeel(&lnf); knob_COMPRESSOR_ATTACK_WOR8.setDoubleClickReturnValue(true,10.0f); addAndMakeVisible(knob_COMPRESSOR_ATTACK_WOR8); lbl_COMPRESSOR_ATTACK_WOR8.setText("COMPRESSOR ATTACK",juce::dontSendNotification); lbl_COMPRESSOR_ATTACK_WOR8.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_ATTACK_WOR8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_ATTACK_WOR8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_ATTACK_WOR8);
    knob_COMPRESSOR_RELEASE_WOR8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_RELEASE_WOR8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_RELEASE_WOR8.setLookAndFeel(&lnf); knob_COMPRESSOR_RELEASE_WOR8.setDoubleClickReturnValue(true,150.0f); addAndMakeVisible(knob_COMPRESSOR_RELEASE_WOR8); lbl_COMPRESSOR_RELEASE_WOR8.setText("COMPRESSOR RELEASE",juce::dontSendNotification); lbl_COMPRESSOR_RELEASE_WOR8.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_RELEASE_WOR8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_RELEASE_WOR8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_RELEASE_WOR8);
    knob_COMPRESSOR_MAKEUP_WOR8.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_COMPRESSOR_MAKEUP_WOR8.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_COMPRESSOR_MAKEUP_WOR8.setLookAndFeel(&lnf); knob_COMPRESSOR_MAKEUP_WOR8.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_COMPRESSOR_MAKEUP_WOR8); lbl_COMPRESSOR_MAKEUP_WOR8.setText("COMPRESSOR MAKEUP",juce::dontSendNotification); lbl_COMPRESSOR_MAKEUP_WOR8.setJustificationType(juce::Justification::centred); lbl_COMPRESSOR_MAKEUP_WOR8.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_COMPRESSOR_MAKEUP_WOR8.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_COMPRESSOR_MAKEUP_WOR8);
    knob_OUTPUT_GAIN.setSliderStyle(juce::Slider::RotaryVerticalDrag); knob_OUTPUT_GAIN.setTextBoxStyle(juce::Slider::TextBoxBelow,false,112,16); knob_OUTPUT_GAIN.setLookAndFeel(&lnf); knob_OUTPUT_GAIN.setDoubleClickReturnValue(true,0.0f); addAndMakeVisible(knob_OUTPUT_GAIN); lbl_OUTPUT_GAIN.setText("OUTPUT",juce::dontSendNotification); lbl_OUTPUT_GAIN.setJustificationType(juce::Justification::centred); lbl_OUTPUT_GAIN.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),9.5f,juce::Font::bold)); lbl_OUTPUT_GAIN.setColour(juce::Label::textColourId,juce::Colour(0xffe8eaf0).withAlpha(0.6f)); addAndMakeVisible(lbl_OUTPUT_GAIN);
}
VelvetAudioProcessorEditor::~VelvetAudioProcessorEditor() { setLookAndFeel(nullptr); }
void VelvetAudioProcessorEditor::paint(juce::Graphics& g) {
    g.fillAll(juce::Colour(0xff0d1117));
    g.setColour(juce::Colour(0xff161b22)); g.fillRect(0,0,520,44);
    g.setColour(juce::Colour(0xff4d8bff).withAlpha(0.2f)); g.fillRect(0,43,520,1);
    g.setColour(juce::Colour(0xffe8eaf0).withAlpha(0.4f)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),11.0f,juce::Font::bold));
    g.drawText("ARCHERGATE",14,0,520-28,44,juce::Justification::centredLeft,false);
    g.setColour(juce::Colour(0xff4d8bff)); g.setFont(juce::Font(juce::Font::getDefaultSansSerifFontName(),15.0f,juce::Font::bold));
    g.drawText("VELVET",14,0,520-28,44,juce::Justification::centredRight,false);
}
void VelvetAudioProcessorEditor::resized() {
    knob_INPUT_GAIN.setBounds(24,60,112,86); lbl_INPUT_GAIN.setBounds(20,146,120,14);
    knob_GAIN_GAIN_DB_T2EC.setBounds(144,60,112,86); lbl_GAIN_GAIN_DB_T2EC.setBounds(140,146,120,14);
    knob_DELAY_DELAY_MS_KENU.setBounds(264,60,112,86); lbl_DELAY_DELAY_MS_KENU.setBounds(260,146,120,14);
    knob_DELAY_FEEDBACK_KENU.setBounds(384,60,112,86); lbl_DELAY_FEEDBACK_KENU.setBounds(380,146,120,14);
    knob_DELAY_MIX_KENU.setBounds(24,168,112,86); lbl_DELAY_MIX_KENU.setBounds(20,254,120,14);
    knob_COMPRESSOR_THRESHOLD_WOR8.setBounds(144,168,112,86); lbl_COMPRESSOR_THRESHOLD_WOR8.setBounds(140,254,120,14);
    knob_COMPRESSOR_RATIO_WOR8.setBounds(264,168,112,86); lbl_COMPRESSOR_RATIO_WOR8.setBounds(260,254,120,14);
    knob_COMPRESSOR_ATTACK_WOR8.setBounds(384,168,112,86); lbl_COMPRESSOR_ATTACK_WOR8.setBounds(380,254,120,14);
    knob_COMPRESSOR_RELEASE_WOR8.setBounds(24,276,112,86); lbl_COMPRESSOR_RELEASE_WOR8.setBounds(20,362,120,14);
    knob_COMPRESSOR_MAKEUP_WOR8.setBounds(144,276,112,86); lbl_COMPRESSOR_MAKEUP_WOR8.setBounds(140,362,120,14);
    knob_OUTPUT_GAIN.setBounds(264,276,112,86); lbl_OUTPUT_GAIN.setBounds(260,362,120,14);
}
